### PR TITLE
Submission activity list

### PR DESCRIPTION
**Pull request by Sahid-m**
# Added ActivityList :

image

This Accepts an Array of Objects with value Name , Username , position , time and IsAnswerCorrect and Displaces them there is also an variable to edit how many people to view in one page

### CODE REVIEW

**Comment by hkirat** [comment]
please resolve conflicts

**Comment by hkirat** [comment]
please resolve conflicts

**Comment by Sahid-m** [comment]
Im New to development so just check the code as well before Ive changed Card as you had max width to 457 px

**Pull request merged**
